### ISSUE TITLE
When spiderfyOnMaxZoom is disabled, zoomToBoundsOnClick on the formerly spiderified clusters don't work anymore

### ISSUE THREAD

**Issue by toniopelo** [Leaflet/Leaflet.markercluster#692]

**Comment by nikolauskrismer** [comment]
Same issue for me here...
... zoom to markers does work for lower zoom levels.
For maxZoon behaviour works up to version 0.4.x, but not anymore with v0.5.x or v1.0-RCs

**Comment by ghybs** [comment]
Hi,

Not sure exactly what is the behaviour that you are expecting?
Please could you provide more details, share some code, and reproduce your issue on playground / JSBin / Plunker / JSFiddle?

Looks working for me with Leaflet 1.0.0-rc.2 and MCG 1.0.0-rc.1, but again, I may consider as normal something that you do not expect.
https://jsfiddle.net/z92L4y17/2/

By the way, it looks like I forgot to port PR #657 into `leaflet-0.7` branch, so that fix is missing in `v0.5.0` tag unfortunately… not sure if that is what you need, as you seem to say that 1.0.0 also do not work for your case?

**Comment by nikolauskrismer** [comment]
Looks like missing PR is what we are talking about here...
... I just double-checked and I was wrong when saying that it does not work in v1.0RCs.

I can not get v1.0 to work right now (seems to be related to webpack and leaflet... when using window.L.markerClusterGroup I get the error that addEventParent is not a function)

**Comment by ghybs** [comment]
Thank you for the feedback!

`addEventParent` is new with Leaflet 1.0.
Note that Leaflet.markercluster (MCG) 1.0.0-rc.1 requires Leaflet 1.0.0-rc.1 at least.

If you have to stick with Leaflet 0.7.7, you should stay with MCG 0.5.0 (plus PR 657 if it solves your issue).

**Comment by nikolauskrismer** [comment]
I thought that I tested MCG with leaflet 1.0.0-rc.3 when I got this message, but after double-checking I have to admit that I was wrong.

The problem was another plugin (leaflet.locatecontrol) which replaced my 1.0.0-rc.3 leaflet reference in package.json with the old 0.7.7 version.

However, MCG works as expected in version 1.0.0-rc.1 (also with rc.3 of leaflet). So yes... the problem in v0.5.0 is the missing PR.

Thanks for your advice :+1:
